# Generated by Django 4.2.5 on 2023-11-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_groups',
        ),
    ]
