# Generated by Django 4.2.5 on 2023-11-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_description'),
        ('user', '0002_remove_customuser_custom_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usercart', to='products.product'),
        ),
    ]
