# Generated by Django 4.2.5 on 2023-11-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_description'),
        ('user', '0003_customuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usercart', to='products.product'),
        ),
    ]
