# Generated by Django 4.2.5 on 2023-10-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_items_order_cart_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_item_id',
            new_name='cart_item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
