# Generated by Django 4.2.5 on 2023-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='cart_item_id',
        ),
    ]
