# Generated by Django 4.2.5 on 2023-11-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_cart_item_id_order_cart_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
