# Generated by Django 4.2.5 on 2023-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='product',
        ),
        migrations.AddField(
            model_name='temp',
            name='categories',
            field=models.ManyToManyField(to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='products.category'),
        ),
    ]
