# Generated by Django 4.2.5 on 2023-10-03 10:39

from django.db import migrations, models

from decimal import Decimal

def convert_decimal_to_integer(apps, schema_editor):
    product = apps.get_model('products', 'Product')
    for obj in product.objects.all():
        obj.rating = int(Decimal(obj.rating).quantize(Decimal('1')))


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),

        migrations.RunPython(convert_decimal_to_integer),
    ]
