# Generated by Django 4.2.5 on 2023-12-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_remove_cart_usercart_cartitem_cart_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
