# Generated by Django 4.2.5 on 2023-12-01 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_remove_product_description'),
        ('shopping_cart', '0008_remove_cart_product_remove_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='usercart',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='shopping_cart.CartItem', to='products.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='usercart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.cart'),
        ),
    ]
