# Generated by Django 4.2.5 on 2023-09-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='year',
            field=models.IntegerField(default='2014', null=True),
        ),
    ]
