# Generated by Django 4.2.5 on 2023-09-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_author_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='album_title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_title',
        ),
    ]
