# Generated by Django 4.2.5 on 2023-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(db_column='custom_column_name', max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
