# Generated by Django 4.2.5 on 2023-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_mynewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynewmodel',
            name='my_field',
            field=models.CharField(db_column='custom_column_name', max_length=50, verbose_name='Field Name'),
        ),
        migrations.AlterModelTable(
            name='mynewmodel',
            table='"naya_model"',
        ),
    ]
