# Generated by Django 4.2.5 on 2023-11-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_mynewmodel_my_field_alter_mynewmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynewmodel',
            options={'verbose_name_plural': 'my names'},
        ),
    ]
