# Generated by Django 4.2.5 on 2023-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_mynewmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynewmodel',
            options={'verbose_name': 'hii', 'verbose_name_plural': 'my name'},
        ),
        migrations.AlterField(
            model_name='mynewmodel',
            name='my_field',
            field=models.CharField(db_column='custom_column_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='mynewmodel',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='naam'),
        ),
    ]
