# Generated by Django 4.2.5 on 2023-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_mynewmodel_options_alter_mynewmodel_my_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynewmodel',
            name='my_field',
            field=models.CharField(db_column='custom_column_name', max_length=50, verbose_name='Field Name'),
        ),
    ]
