# Generated by Django 4.2.5 on 2023-11-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_mynewmodel_my_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynewmodel',
            options={'verbose_name_plural': 'my name'},
        ),
    ]
