# Generated by Django 4.2.5 on 2023-12-01 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_cart', '0010_alter_cart_table_alter_cartitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='usercart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user name'),
        ),
    ]
